apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: complete-devops-app

  template:
    metadata:
      labels:
        app: complete-devops-app

    spec:
      containers:
        - name: app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
          - name: APP_MESSAGE
            valueFrom:
              secretKeyRef:
                name: complete-devops-app-secret
                key: APP_MESSAGE

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
