replicaCount: 2

image:
  repository: 521464398227.dkr.ecr.us-east-1.amazonaws.com/complete-devops-automation
  tag: "779ab6d56496"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
